server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/umcProject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace  # 3.0

